name: CI-Main branch
on:
  push:
    branches:
      - main


jobs:
  common:
    uses: https://github.com/Uzma-Solera/github-actions-reusable.git/.github/workflows/ci-main.yml
    with:
      component_name: cart
      app_type: nodejs
